# Generated by Django 5.2.3 on 2025-07-08 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('VH', 'Very High'), ('H', 'High'), ('M', 'Medium'), ('L', 'Low'), ('VL', 'Very Low')], default='Medium', max_length=2),
        ),
    ]
