# Generated by Django 5.2.3 on 2025-07-08 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_task_description_alter_task_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('VH', 'Very High'), ('H', 'High'), ('M', 'Medium'), ('L', 'Low'), ('VL', 'Very Low')], max_length=2),
        ),
    ]
