# Generated by Django 5.2.3 on 2025-07-08 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_task_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('VH', 'Very High'), ('H', 'High'), ('M', 'Medium'), ('L', 'Low'), ('VL', 'Very Low')], default='M', max_length=2),
        ),
    ]
