# Generated by Django 5.2.3 on 2025-07-08 12:03

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_task_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Date',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='task',
            name='date',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.date'),
        ),
    ]
